# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac3f59fdf7c6f8c9114906d793181c7d1f02b577d61067560783fa54e0814ca56a280256e9ea7d4c422704cc4157e43920b6564ba175bdc79ec11be78adb998a

test:
  secret_key_base: 79ac480569a9f4bb3e5ad04f0edaacabad7abf4be3a80411db96f52701bf8247f12bf4fc8163f814fafb218fd6bac40f83b17353b3ed8d7ca7ed2b6c09d0a6af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
